package io.jaiclaw.shell.commands.setup.config;

import io.jaiclaw.shell.commands.setup.OnboardResult;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import java.util.Set;

/**
 * Writes a {@code .env.op.tpl} 1Password template next to the
 * wizard's regular {@code .env} output.
 *
 * <p>The template is a list of {@code KEY=op://vault/item/field}
 * lines — references only, no plaintext. {@code op run --env-file=}
 * resolves them at process start. The launcher's
 * {@code --use-1password} flag wires the re-exec.
 *
 * <p>Item/field defaults follow a simple heuristic: the env-var name
 * is split on the first underscore. The prefix (lowercased) becomes
 * the item title, the suffix (lowercased, hyphenated) becomes the
 * field. For example {@code ANTHROPIC_API_KEY} → item {@code anthropic},
 * field {@code api-key}. Operators with different vault layouts should
 * edit the generated file or use the {@code bin/jaiclaw
 * setup-1password} bash command for per-key prompts.
 */
@Component
public final class OnePasswordTemplateWriter {

    /**
     * Write the template if the result has a {@link
     * OnboardResult.OnePasswordConfig} set. No-op otherwise.
     *
     * @param result the wizard's collected state
     * @param configDir the same directory the regular {@code .env}
     *                  was written to
     * @return the path of the written file, or {@code null} if not
     *         configured
     */
    public Path writeIfConfigured(OnboardResult result, Path configDir) throws IOException {
        OnboardResult.OnePasswordConfig op = result.onePassword();
        if (op == null) {
            return null;
        }
        Path tpl = configDir.resolve(".env.op.tpl");
        StringBuilder sb = new StringBuilder();
        sb.append("# JaiClaw 1Password template — generated by the setup wizard.\n");
        sb.append("# Format: KEY=op://<vault>/<item>/<field>\n");
        sb.append("# Resolved at startup via: jaiclaw --use-1password <command>\n");
        sb.append("# This file contains REFERENCES only. Safe to commit to a private repo.\n");
        sb.append("#\n");
        sb.append("# Edit item/field paths to match your actual 1Password layout, or run\n");
        sb.append("# 'bin/jaiclaw setup-1password' for an interactive per-key walkthrough.\n");
        sb.append("\n");
        for (String envKey : op.envKeys()) {
            sb.append(envKey)
              .append('=')
              .append(buildRef(op.vault(), envKey))
              .append('\n');
        }
        Files.writeString(tpl, sb.toString(), StandardCharsets.UTF_8);
        // 0600 — same posture as a .env. Tightens an otherwise umask-
        // dependent default. Not supported on Windows; ignored there.
        try {
            Set<PosixFilePermission> perms = EnumSet.of(
                    PosixFilePermission.OWNER_READ,
                    PosixFilePermission.OWNER_WRITE);
            Files.setPosixFilePermissions(tpl, perms);
        } catch (UnsupportedOperationException ignored) {
            // Non-POSIX filesystem (Windows). The OS-level ACLs already
            // restrict writes to the user.
        }
        return tpl;
    }

    /**
     * Build an {@code op://} reference from a vault name and an env
     * variable name. Visible-for-testing.
     */
    static String buildRef(String vault, String envKey) {
        int firstUnderscore = envKey.indexOf('_');
        String item;
        String field;
        if (firstUnderscore < 0) {
            // No underscore — use the key itself as the item, "value" as the field.
            item = envKey.toLowerCase();
            field = "value";
        } else {
            item = envKey.substring(0, firstUnderscore).toLowerCase();
            field = envKey.substring(firstUnderscore + 1)
                          .toLowerCase()
                          .replace('_', '-');
        }
        return "op://" + vault + "/" + item + "/" + field;
    }
}
