package io.jclaw.shell.commands.setup.config;

import io.jclaw.shell.commands.setup.OnboardResult;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Component
public class YamlConfigWriter {

    public String generate(OnboardResult result) {
        StringBuilder sb = new StringBuilder();
        sb.append("# JClaw configuration - generated by setup wizard\n");
        sb.append("jclaw:\n");
        sb.append("  identity:\n");
        sb.append("    name: ").append(result.assistantName()).append("\n");
        sb.append("  agent:\n");
        sb.append("    default-agent: default\n");
        sb.append("    agents:\n");
        sb.append("      default:\n");
        sb.append("        model:\n");
        sb.append("          primary: ").append(result.llmModel()).append("\n");
        appendFallbacks(sb, result);
        sb.append("        tools:\n");
        sb.append("          profile: coding\n");
        sb.append("  tools:\n");
        sb.append("    profile: coding\n");
        sb.append("  skills:\n");
        sb.append("    allow-bundled:\n");
        sb.append("      - \"*\"\n");
        sb.append("  plugins:\n");
        sb.append("    enabled: true\n");
        sb.append("\n");

        // Spring AI provider config
        sb.append("spring:\n");
        sb.append("  ai:\n");
        appendProviderConfig(sb, result);

        // Server config (manual mode)
        if (result.isManual()) {
            sb.append("\nserver:\n");
            sb.append("  port: ").append(result.serverPort()).append("\n");
            sb.append("  address: ").append(result.bindAddress()).append("\n");
        }

        return sb.toString();
    }

    public void write(OnboardResult result) throws IOException {
        Path dir = result.configDir();
        Files.createDirectories(dir);
        Path file = ConfigLocation.yamlFile(dir);
        Files.writeString(file, generate(result));
    }

    private void appendFallbacks(StringBuilder sb, OnboardResult result) {
        String fallback = switch (result.llmProvider()) {
            case "openai" -> "gpt-4o-mini";
            case "anthropic" -> "claude-haiku-4-5-20251001";
            default -> null;
        };
        if (fallback != null) {
            sb.append("          fallbacks:\n");
            sb.append("            - ").append(fallback).append("\n");
        }
    }

    private void appendProviderConfig(StringBuilder sb, OnboardResult result) {
        switch (result.llmProvider()) {
            case "openai" -> {
                sb.append("    openai:\n");
                sb.append("      api-key: ${OPENAI_API_KEY}\n");
            }
            case "anthropic" -> {
                sb.append("    anthropic:\n");
                sb.append("      api-key: ${ANTHROPIC_API_KEY}\n");
            }
            case "ollama" -> {
                sb.append("    ollama:\n");
                sb.append("      base-url: ").append(result.ollamaBaseUrl()).append("\n");
            }
        }
    }
}
